### ISSUE TITLE
Unused value in utee macro

### ISSUE THREAD

**Issue by ionut-arm** [mesalock-linux/rust-optee-trustzone-sdk#10]
Hello,

I was looking through the code and saw that in the `ta_destroy` macro definition there's a boolean value that's ignored. 

https://github.com/mesalock-linux/rust-optee-trustzone-sdk/blob/master/optee-utee/macros/src/lib.rs#L230

I think the outcome is that you're not checking the return type at compile time.

**Comment by mssun** [comment]
Fixed. Thank you so much!
