### ISSUE TITLE
Wiki Update

### ISSUE THREAD

**Issue by SimonWan** [mesalock-linux/rust-optee-trustzone-sdk#11]
The [QEMU Wiki](https://github.com/mesalock-linux/rust-optee-trustzone-sdk/wiki/Getting-started-with-OPTEE-for-QEMU-ARMv8) includes 2 invalid links:

1) the dependencies' instruction should refer to this page now: https://optee.readthedocs.io/en/latest/building/prerequisites.html.

2) The Dockerfile can't be found.

**Comment by mssun** [comment]
Fixed.
