### ISSUE TITLE
make QEMU_VIRTFS_ENABLE=y CFG_TEE_RAM_VA_SIZE=0x00300000 failed

### ISSUE THREAD

**Issue by laurencechan** [mesalock-linux/rust-optee-trustzone-sdk#13]
Hi, When I execuited the command "sudo make QEMU_VIRTFS_ENABLE=y CFG_TEE_RAM_VA_SIZE=0x00300000 failed" in  path "/home/laurencechan/rust-optee-trustzone-sdk/optee-qemuv8-3.4.0/build" , but got this error message.

```
LINK    aarch64-softmmu/qemu-system-aarch64
make[1]: Leaving directory '/home/laurencechan/rust-optee-trustzone-sdk/optee-qemuv8-3.4.0/qemu'
make -C /home/laurencechan/rust-optee-trustzone-sdk/optee-qemuv8-3.4.0/build/../soc_term
make[1]: Entering directory '/home/laurencechan/rust-optee-trustzone-sdk/optee-qemuv8-3.4.0/soc_term'
gcc -o soc_term soc_term.o
/usr/bin/ld: soc_term.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: soc_term.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: soc_term.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: soc_term.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: soc_term.o: Relocations in generic ELF (EM: 183)
soc_term.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
Makefile:9: recipe for target 'soc_term' failed
make[1]: *** [soc_term] Error 1
make[1]: Leaving directory '/home/laurencechan/rust-optee-trustzone-sdk/optee-qemuv8-3.4.0/soc_term'
Makefile:146: recipe for target 'soc-term' failed
make: *** [soc-term] Error 2

```

**Comment by laurencechan** [comment]
Maybe I just did wrong. After I compiled all the examples, what should I do next?
follow the instuction in the link?
![image](https://user-images.githubusercontent.com/17173306/70435773-aefcc480-1ac2-11ea-92a8-295a3c213bda.png)

**Comment by mssun** [comment]
Seems that you failed to build QEMU. I believe there is something wrong with the dependencies. Can you use our Dockerfile as the building environment and try again.

**Comment by mssun** [comment]
Actually, there is a daily Travis CI job to run the code with the following steps:

https://github.com/mesalock-linux/rust-optee-trustzone-sdk/blob/master/.travis.yml

**Comment by laurencechan** [comment]
> Seems that you failed to build QEMU. I believe there is something wrong with the dependencies. Can you use our Dockerfile as the building environment and try again.

After I finished "make examples"， How should I build the QEMU?
Start from the first red frame or the second？
![image](https://user-images.githubusercontent.com/17173306/70487978-17cf5580-1b32-11ea-8fad-12cf5de90691.png)

**Comment by laurencechan** [comment]
> Seems that you failed to build QEMU. I believe there is something wrong with the dependencies. Can you use our Dockerfile as the building environment and try again.

How to use your dockerfile? I did not find any docs from your project about this except a dockerfile. I just build a image from it and run a docker from this image without any specified args and it will runs well?

**Comment by laurencechan** [comment]
I exec the container and it works well.
```
#sudo docker run -it -d --network host --name complie -v$(pwd):/rust-optee-trustzone-sdk -w /rust-optee-trustzone-sdk mesalocklinux/rust-optee-trustzone-sdk-qemuv8-ci:v1 /bin/bash
#sudo docker exec -it complie /bin/bash
# cd ci/
# ls
ci.sh
 ./ci.sh 
+ pushd ../tests
/rust-optee-trustzone-sdk/tests /rust-optee-trustzone-sdk/ci
+ ./test_hello_world.sh
+ rm -rf screenlog.0
+ rm -rf optee-qemuv8-3.4.0
+ rm -rf shared
+ source /root/.bashrc
++ '[' -z '' ']'
++ return
+ curl --connect-timeout 200 http://mesalock-linux.org/assets/optee-qemuv8-3.4.0.tar.gz
+ tar zxv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 34.1M    0 15789    0     0    970      0 10:14:54  0:00:16 10:14:38  3332optee-qemuv8-3.4.0/

```
But outside the container, it won't. seems wired.
```
$sudo docker run --rm -it --network host --dns 8.8.4.4 -v$(pwd):/rust-optee-trustzone-sdk -w /rust-optee-trustzone-sdk mesalocklinux/rust-optee-trustzone-sdk-qemuv8-ci:v1 bash -c "cd ci && ./ci.sh"
+ pushd ../tests
/rust-optee-trustzone-sdk/tests /rust-optee-trustzone-sdk/ci
+ ./test_hello_world.sh
+ rm -rf screenlog.0
+ rm -rf optee-qemuv8-3.4.0
+ rm -rf shared
+ source /root/.bashrc
++ '[' -z '' ']'
++ return
+ tar zxv
+ curl --connect-timeout 200 http://mesalock-linux.org/assets/optee-qemuv8-3.4.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0curl: (6) Could not resolve host: mesalock-linux.org

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by laurencechan** [comment]
> Actually, there is a daily Travis CI job to run the code with the following steps:
> 
> https://github.com/mesalock-linux/rust-optee-trustzone-sdk/blob/master/.travis.yml

Hi @mssun , I  still Got another question. If I use rust write a TA, is it possible to use C to write the corresponding CA?

**Comment by mssun** [comment]
Yes, you can use any language to write CA (same as OPTEE's client).

**Comment by laurencechan** [comment]
> Yes, you can use any language to write CA (same as OPTEE's client).

@mssun I see, thank you~~

**Comment by SimonWan** [comment]
Looks like the titled issue has been resolved. Feel free to reopen the issue if it's not.
