### ISSUE TITLE
How can I create a OPTEE snapshots?

### ISSUE THREAD

**Issue by Mangoymd** [mesalock-linux/rust-optee-trustzone-sdk#16]
I'm new to OPTEE. I find that every time I need run `make run-only` to start OPTEE environment(qemu_v8).
But how do I save a new file I created in the OPTEE environment to my host OS device?
Or how can I create a OPTEE snapshots?

**Comment by mssun** [comment]
Thanks for asking. You can use `QEMU_VIRTFS_HOST_DIR` to share a directory with host and guest.

Also, QEMU support to create snapshot [1] [2].

[1] https://wiki.qemu.org/index.php/Features/Snapshots
[2] https://wiki.qemu.org/Documentation/CreateSnapshot

**Comment by Mangoymd** [comment]
Thanks！
Sharing folders is very convenient！
