### ISSUE TITLE
如何解决git submodule update --init过慢问题？

### ISSUE THREAD

**Issue by qiuweixuan** [mesalock-linux/rust-optee-trustzone-sdk#9]
您好，我是一名华工学生，主要研究optee上的应用（比如实现wpa3的dragonfly协议），由于GP规范大整数API较为难用，因此对您的项目非常感兴趣，希望能够使用rust更方便实现TA。
现在遇到一个问题，git submodule update --init中optee资源在外网，下载速度过慢。
之前我研究optee时，使用repo init -u https://github.com/OP-TEE/manifest.git -m ${TARGET}.xml [-b ${BRANCH}]进行下载，其中${TARGET}.xml指定的是运行环境，${BRANCH}指定的是选择的版本分支，由于资源在外网缘故，需要在上述命令行添加--repo-url=git://codeaurora.org/tools/repo.git来指定下载url链接。
不知道您这边能否加速git下载，如果不行，我自己去下载optee源码放到相应目录下，是否会有项目兼容性问题？

**Comment by mssun** [comment]
Hi, thanks for the report. I think the biggest issue is the rust code, which is about 948M. You can find some other sources (mirrors of GitHub) or by setting up proxy to download the Rust code.

```
➜  rust-optee-trustzone-sdk git:(master) du -sh *
4.0K	Dockerfile
 12K	LICENSE
4.0K	Makefile
4.0K	README.md
4.0K	aarch64-unknown-optee-trustzone.json
4.0K	arm-unknown-optee-trustzone.json
4.0K	ci
4.0K	environment
1.2M	examples
 14M	optee
 88K	optee-teec
316K	optee-utee
948M	rust
4.0K	rust-toolchain
 56K	tests
```
